/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'Augustine' at '9/20/16 11:06 PM' with Gradle 2.13
 *
 * @author Augustine, @date 9/20/16 11:06 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
